export type Vertical = "property" | "ev" | "digital" | "fnb" | "health" | "travel";
export type Difficulty = "easy" | "medium" | "hard";

export interface Task {
  id: string;
  title: string;
  description: string;
  points: number;
  vertical: Vertical;
  difficulty: Difficulty;
  timeEstimate: string;
  steps: string[];
}

export interface Reward {
  id: string;
  title: string;
  description: string;
  pointCost: number;
  priceMYR: number;
  vertical: Vertical;
  vendor: string;
  value: string;
  stock: number;
}

export const VERTICAL_LABELS: Record<Vertical, string> = {
  property: "Property",
  ev: "EV & Mobility",
  digital: "Digital",
  fnb: "F&B & Lifestyle",
  health: "Health & Wellness",
  travel: "Travel & Tourism",
};

export const VERTICAL_COLORS: Record<Vertical, string> = {
  property: "bg-blue-100 text-blue-700",
  ev: "bg-green-100 text-green-700",
  digital: "bg-violet-100 text-violet-700",
  fnb: "bg-orange-100 text-orange-700",
  health: "bg-rose-100 text-rose-700",
  travel: "bg-cyan-100 text-cyan-700",
};

export const tasks: Task[] = [
  // ── Property ──
  {
    id: "refer-tenant",
    title: "Refer a Tenant",
    description: "Refer a contact who successfully rents a property through our partner agents.",
    points: 5000,
    vertical: "property",
    difficulty: "medium",
    timeEstimate: "1–2 weeks",
    steps: [
      "Share your unique referral link with a potential tenant",
      "They sign up using your link",
      "They complete a successful tenancy agreement",
      "Points credited within 7 days",
    ],
  },
  {
    id: "property-survey",
    title: "Complete Property Survey",
    description: "Fill out a 5-minute survey about your property preferences for our partner developers.",
    points: 500,
    vertical: "property",
    difficulty: "easy",
    timeEstimate: "5 mins",
    steps: [
      "Open the survey form",
      "Answer all questions honestly",
      "Submit your response",
      "Points credited within 1 hour",
    ],
  },
  {
    id: "property-expo",
    title: "Attend a Property Expo",
    description: "Visit any GanjaranX partner property expo and register your attendance to earn points.",
    points: 800,
    vertical: "property",
    difficulty: "easy",
    timeEstimate: "2–3 hours",
    steps: [
      "Check the upcoming expo schedule in the app",
      "Register your slot online",
      "Attend and scan the check-in QR at the entrance",
      "Points credited within 24 hours",
    ],
  },
  {
    id: "refer-property-buyer",
    title: "Refer a Property Buyer",
    description: "Refer someone who successfully purchases a property through a GanjaranX partner developer.",
    points: 15000,
    vertical: "property",
    difficulty: "hard",
    timeEstimate: "1–3 months",
    steps: [
      "Share your referral link with a potential buyer",
      "They register with your referral code",
      "They sign a Sales and Purchase Agreement (SPA)",
      "Points credited after SPA is verified — within 14 days",
    ],
  },

  // ── EV & Mobility ──
  {
    id: "ev-test-drive",
    title: "Test Drive an EV",
    description: "Book and complete a test drive at any participating EV dealership.",
    points: 1500,
    vertical: "ev",
    difficulty: "easy",
    timeEstimate: "2–3 hours",
    steps: [
      "Select a participating dealership from the list",
      "Book your preferred time slot",
      "Attend the test drive and scan the QR code at the venue",
      "Points credited instantly",
    ],
  },
  {
    id: "ev-charging-signup",
    title: "Subscribe to EV Charging Plan",
    description: "Subscribe to a monthly EV charging plan with any of our mobility partners.",
    points: 3000,
    vertical: "ev",
    difficulty: "medium",
    timeEstimate: "30 mins",
    steps: [
      "Browse available charging plans",
      "Select and subscribe to a plan",
      "Complete your first charge session",
      "Points credited within 24 hours",
    ],
  },
  {
    id: "ev-refer-buyer",
    title: "Refer an EV Buyer",
    description: "Refer someone who purchases an EV through a GanjaranX partner dealership.",
    points: 8000,
    vertical: "ev",
    difficulty: "hard",
    timeEstimate: "1–4 weeks",
    steps: [
      "Share your referral link with a potential EV buyer",
      "They book a test drive using your code",
      "They complete the purchase",
      "Points credited after purchase confirmation",
    ],
  },
  {
    id: "ev-photo-challenge",
    title: "EV Photo Challenge",
    description: "Share a photo at an EV charging station or with an electric vehicle and tag GanjaranX.",
    points: 250,
    vertical: "ev",
    difficulty: "easy",
    timeEstimate: "15 mins",
    steps: [
      "Take a creative photo at an EV charging point or with an EV",
      "Post on Instagram or Facebook and tag @GanjaranX",
      "Submit your post link in the app",
      "Points credited after verification",
    ],
  },

  // ── Digital ──
  {
    id: "store-checkin",
    title: "Check In at Partner Store",
    description: "Visit and check in at any GanjaranX partner outlet to earn quick points.",
    points: 200,
    vertical: "digital",
    difficulty: "easy",
    timeEstimate: "15 mins",
    steps: [
      "Find a partner store near you",
      "Visit the store and open GanjaranX",
      "Tap Check In and scan the store QR code",
      "Points credited immediately",
    ],
  },
  {
    id: "watch-sponsored-video",
    title: "Watch a Sponsored Video",
    description: "Watch a short sponsored video from our brand partners and answer a quick poll.",
    points: 100,
    vertical: "digital",
    difficulty: "easy",
    timeEstimate: "3 mins",
    steps: [
      "Choose a video from the sponsored feed",
      "Watch the full video without skipping",
      "Answer a quick poll about the ad",
      "Points credited instantly",
    ],
  },
  {
    id: "online-survey",
    title: "Complete an Online Survey",
    description: "Share your opinions in a 10-minute branded survey and get rewarded for your time.",
    points: 350,
    vertical: "digital",
    difficulty: "easy",
    timeEstimate: "10 mins",
    steps: [
      "Pick an available survey from the digital feed",
      "Complete all questions truthfully",
      "Submit your responses",
      "Points credited within 2 hours",
    ],
  },
  {
    id: "app-review",
    title: "Leave an App Review",
    description: "Leave an honest review of GanjaranX on the App Store or Google Play.",
    points: 500,
    vertical: "digital",
    difficulty: "easy",
    timeEstimate: "5 mins",
    steps: [
      "Open the App Store or Google Play",
      "Find GanjaranX and leave a review",
      "Take a screenshot of your review",
      "Submit the screenshot in the app for verification",
    ],
  },

  // ── F&B & Lifestyle ──
  {
    id: "restaurant-review",
    title: "Dine & Review",
    description: "Visit a partner restaurant, dine in, and leave a verified review on our platform.",
    points: 400,
    vertical: "fnb",
    difficulty: "easy",
    timeEstimate: "1 hour",
    steps: [
      "Choose a partner restaurant near you",
      "Dine in and scan the table QR code",
      "Submit your review with a photo",
      "Points credited within 24 hours",
    ],
  },
  {
    id: "grocery-spend",
    title: "Spend RM 100 at Partner Grocer",
    description: "Shop at any GanjaranX partner supermarket and earn bonus points on your spend.",
    points: 800,
    vertical: "fnb",
    difficulty: "easy",
    timeEstimate: "30 mins",
    steps: [
      "Shop at any participating supermarket",
      "Spend a minimum of RM 100",
      "Scan your receipt in the app",
      "Points credited within 48 hours",
    ],
  },
  {
    id: "food-delivery-order",
    title: "Order via GanjaranX Delivery",
    description: "Place your first food delivery order through our partner delivery platform and earn points.",
    points: 300,
    vertical: "fnb",
    difficulty: "easy",
    timeEstimate: "30 mins",
    steps: [
      "Open the GanjaranX-linked food delivery link",
      "Place an order of minimum RM 20",
      "Use your GanjaranX promo code at checkout",
      "Points credited after order is delivered",
    ],
  },
  {
    id: "fnb-referral",
    title: "Refer a Friend to a Partner Restaurant",
    description: "Bring a friend to dine at a partner restaurant and earn bonus points for the referral.",
    points: 600,
    vertical: "fnb",
    difficulty: "easy",
    timeEstimate: "1 hour",
    steps: [
      "Share your referral code with a friend",
      "Dine together at any partner restaurant",
      "Both parties scan the table QR",
      "Referral bonus credited within 24 hours",
    ],
  },

  // ── Health & Wellness ──
  {
    id: "gym-trial",
    title: "Try a Gym Free Trial",
    description: "Book and attend a free trial session at any GanjaranX partner gym.",
    points: 600,
    vertical: "health",
    difficulty: "easy",
    timeEstimate: "2 hours",
    steps: [
      "Select a partner gym from the list",
      "Book your free trial session",
      "Attend the session and check in via QR",
      "Points credited immediately",
    ],
  },
  {
    id: "health-screening",
    title: "Complete a Health Screening",
    description: "Undergo a basic health screening package at a partner clinic or pharmacy.",
    points: 1200,
    vertical: "health",
    difficulty: "medium",
    timeEstimate: "1–2 hours",
    steps: [
      "Find a partner clinic or pharmacy",
      "Book the GanjaranX health screening package",
      "Complete your screening",
      "Upload your results and claim points",
    ],
  },
  {
    id: "wellness-programme",
    title: "Sign Up for a Wellness Programme",
    description: "Enrol in a structured 4-week wellness or fitness programme at a partner centre.",
    points: 2500,
    vertical: "health",
    difficulty: "medium",
    timeEstimate: "4 weeks",
    steps: [
      "Browse available wellness programmes",
      "Register and pay for your chosen programme",
      "Complete at least 4 sessions",
      "Points credited upon programme completion",
    ],
  },
  {
    id: "steps-challenge",
    title: "10,000 Steps Daily Challenge",
    description: "Connect your fitness tracker and hit 10,000 steps a day for 7 consecutive days.",
    points: 1000,
    vertical: "health",
    difficulty: "medium",
    timeEstimate: "7 days",
    steps: [
      "Connect your Google Fit or Apple Health account",
      "Hit 10,000 steps each day for 7 days",
      "GanjaranX automatically tracks your progress",
      "Points credited on day 7",
    ],
  },

  // ── Travel & Tourism ──
  {
    id: "hotel-review",
    title: "Stay & Review a Partner Hotel",
    description: "Book a stay at a partner hotel and submit a detailed review after check-out.",
    points: 2000,
    vertical: "travel",
    difficulty: "medium",
    timeEstimate: "1–2 days",
    steps: [
      "Book any partner hotel through GanjaranX",
      "Complete your stay",
      "Submit a review with photos within 48 hours",
      "Points credited after review is verified",
    ],
  },
  {
    id: "travel-survey",
    title: "Complete a Travel Preferences Survey",
    description: "Help our travel partners understand your preferences and earn points for your time.",
    points: 300,
    vertical: "travel",
    difficulty: "easy",
    timeEstimate: "5 mins",
    steps: [
      "Open the travel survey form",
      "Answer all questions",
      "Submit your response",
      "Points credited within 1 hour",
    ],
  },
  {
    id: "day-trip-booking",
    title: "Book a Day Trip Package",
    description: "Book and complete a local day trip package through any GanjaranX travel partner.",
    points: 1500,
    vertical: "travel",
    difficulty: "medium",
    timeEstimate: "1 day",
    steps: [
      "Browse available day trip packages",
      "Book and pay for your chosen trip",
      "Complete the day trip",
      "Submit a review photo to claim your points",
    ],
  },
  {
    id: "travel-referral",
    title: "Refer a Travel Booking",
    description: "Refer a friend who books a hotel or travel package through GanjaranX.",
    points: 1200,
    vertical: "travel",
    difficulty: "easy",
    timeEstimate: "Varies",
    steps: [
      "Share your travel referral link",
      "Friend clicks and makes a qualifying booking",
      "Booking is confirmed and completed",
      "Points credited within 7 days",
    ],
  },
];

export const rewards: Reward[] = [
  // ── EV & Mobility ──
  {
    id: "ev-charging-rm50",
    title: "RM 50 EV Charging Credit",
    description: "Top up your EV charging wallet, valid at all ChargEV and IKEA EV stations nationwide.",
    pointCost: 5000,
    priceMYR: 50,
    vertical: "ev",
    vendor: "ChargEV",
    value: "RM 50",
    stock: 200,
  },
  {
    id: "ev-accessories",
    title: "EV Accessories RM 80 Voucher",
    description: "Shop EV cables, adapters, and accessories at any EV Plug partner store.",
    pointCost: 6500,
    priceMYR: 80,
    vertical: "ev",
    vendor: "EV Plug MY",
    value: "RM 80",
    stock: 75,
  },
  {
    id: "ev-home-charger",
    title: "RM 200 Off Home Charger Installation",
    description: "Get RM 200 off the installation of a Type 2 home EV charger by our certified partner.",
    pointCost: 18000,
    priceMYR: 200,
    vertical: "ev",
    vendor: "GreenCharge MY",
    value: "RM 200",
    stock: 30,
  },
  {
    id: "ev-charging-rm20",
    title: "RM 20 EV Charging Credit",
    description: "Quick top-up for your EV charging wallet. Valid at ChargEV stations nationwide.",
    pointCost: 2000,
    priceMYR: 20,
    vertical: "ev",
    vendor: "ChargEV",
    value: "RM 20",
    stock: 500,
  },

  // ── F&B & Lifestyle ──
  {
    id: "fb-voucher-rm30",
    title: "RM 30 F&B Voucher",
    description: "Redeem at any of our 50+ F&B partner outlets across Klang Valley.",
    pointCost: 2500,
    priceMYR: 30,
    vertical: "fnb",
    vendor: "GanjaranX Partners",
    value: "RM 30",
    stock: 500,
  },
  {
    id: "restaurant-voucher-rm50",
    title: "RM 50 Restaurant Voucher",
    description: "Dine at over 100 partner restaurants across Malaysia with this voucher.",
    pointCost: 4500,
    priceMYR: 50,
    vertical: "fnb",
    vendor: "GanjaranX Dining",
    value: "RM 50",
    stock: 300,
  },
  {
    id: "grocery-cashback-rm20",
    title: "RM 20 Grocery Cashback",
    description: "Get RM 20 cashback on your next grocery run at partner supermarkets.",
    pointCost: 1800,
    priceMYR: 20,
    vertical: "fnb",
    vendor: "Jaya Grocer / Village Grocer",
    value: "RM 20",
    stock: 400,
  },
  {
    id: "starbucks-rm20",
    title: "Starbucks RM 20 eGift",
    description: "Enjoy RM 20 credit at any Starbucks outlet in Malaysia. Valid for 6 months.",
    pointCost: 1800,
    priceMYR: 20,
    vertical: "fnb",
    vendor: "Starbucks Malaysia",
    value: "RM 20",
    stock: 250,
  },
  {
    id: "grab-food-rm30",
    title: "GrabFood RM 30 Credit",
    description: "RM 30 in GrabFood credits — order from thousands of restaurants across Malaysia.",
    pointCost: 2800,
    priceMYR: 30,
    vertical: "fnb",
    vendor: "Grab Malaysia",
    value: "RM 30",
    stock: 350,
  },

  // ── Travel & Tourism ──
  {
    id: "hotel-1night",
    title: "1 Night Hotel Stay",
    description: "Enjoy a one-night stay at a 3-star partner hotel. Blackout dates apply.",
    pointCost: 15000,
    priceMYR: 250,
    vertical: "travel",
    vendor: "Best Western Malaysia",
    value: "RM 250",
    stock: 20,
  },
  {
    id: "flight-voucher-rm100",
    title: "RM 100 Flight Voucher",
    description: "Save on your next domestic or short-haul flight with our airline partners.",
    pointCost: 10000,
    priceMYR: 100,
    vertical: "travel",
    vendor: "AirAsia / Batik Air",
    value: "RM 100",
    stock: 150,
  },
  {
    id: "travel-insurance-rm50",
    title: "RM 50 Travel Insurance",
    description: "Get covered for your next trip with a complimentary travel insurance plan.",
    pointCost: 4200,
    priceMYR: 50,
    vertical: "travel",
    vendor: "Etiqa Insurance",
    value: "RM 50",
    stock: 200,
  },
  {
    id: "airbnb-rm150",
    title: "Airbnb RM 150 Credit",
    description: "RM 150 credit towards any Airbnb stay in Malaysia or regionally.",
    pointCost: 14000,
    priceMYR: 150,
    vertical: "travel",
    vendor: "Airbnb",
    value: "RM 150",
    stock: 40,
  },
  {
    id: "hotel-voucher-rm100",
    title: "RM 100 Hotel Voucher",
    description: "Valid for room upgrades, dining, or accommodation at Agoda partner properties.",
    pointCost: 9500,
    priceMYR: 100,
    vertical: "travel",
    vendor: "Agoda Malaysia",
    value: "RM 100",
    stock: 100,
  },

  // ── Health & Wellness ──
  {
    id: "gym-month-pass",
    title: "1-Month Gym Membership",
    description: "Enjoy one month of unlimited gym access at any GanjaranX partner fitness centre.",
    pointCost: 9000,
    priceMYR: 120,
    vertical: "health",
    vendor: "Celebrity Fitness",
    value: "RM 120",
    stock: 60,
  },
  {
    id: "wellness-spa-rm80",
    title: "RM 80 Spa & Wellness Voucher",
    description: "Treat yourself to a relaxing spa session at partner wellness centres nationwide.",
    pointCost: 7000,
    priceMYR: 80,
    vertical: "health",
    vendor: "Rekindle Wellness",
    value: "RM 80",
    stock: 80,
  },
  {
    id: "health-supplement-bundle",
    title: "Health Supplement Bundle",
    description: "A curated bundle of vitamins and supplements from our health partner, delivered to your door.",
    pointCost: 5000,
    priceMYR: 60,
    vertical: "health",
    vendor: "Caring Pharmacy",
    value: "RM 60",
    stock: 120,
  },
  {
    id: "health-screening-voucher",
    title: "Basic Health Screening Voucher",
    description: "Full blood count, cholesterol, blood sugar, and BMI check at a partner clinic.",
    pointCost: 3500,
    priceMYR: 80,
    vertical: "health",
    vendor: "Klinik Mediviron",
    value: "RM 80",
    stock: 90,
  },

  // ── Property ──
  {
    id: "agent-fee-discount",
    title: "Agent Fee Discount Voucher",
    description: "10% off agent fee on your next tenancy agreement through GanjaranX partner agents.",
    pointCost: 4000,
    priceMYR: 300,
    vertical: "property",
    vendor: "PropNex Malaysia",
    value: "Up to RM 300",
    stock: 100,
  },
  {
    id: "property-legal-rm200",
    title: "RM 200 Property Legal Fees Voucher",
    description: "Offset legal fees on your next property purchase or tenancy through our partners.",
    pointCost: 18000,
    priceMYR: 200,
    vertical: "property",
    vendor: "TanSri Law Chambers",
    value: "RM 200",
    stock: 30,
  },
  {
    id: "home-cleaning-rm80",
    title: "Home Cleaning Service Voucher",
    description: "Book a 3-hour professional home cleaning session at your property anywhere in Klang Valley.",
    pointCost: 6000,
    priceMYR: 80,
    vertical: "property",
    vendor: "Helpr MY",
    value: "RM 80",
    stock: 150,
  },

  // ── Digital ──
  {
    id: "legal-drafting",
    title: "Legal Document Drafting",
    description: "Get a one-page legal document drafted by our partner law firm.",
    pointCost: 8000,
    priceMYR: 150,
    vertical: "digital",
    vendor: "LegalEase MY",
    value: "RM 150",
    stock: 50,
  },
  {
    id: "shopee-voucher-rm30",
    title: "Shopee RM 30 Voucher",
    description: "RM 30 Shopee voucher valid sitewide — shop fashion, electronics, groceries & more.",
    pointCost: 2800,
    priceMYR: 30,
    vertical: "digital",
    vendor: "Shopee Malaysia",
    value: "RM 30",
    stock: 300,
  },
  {
    id: "netflix-1month",
    title: "Netflix 1-Month Subscription",
    description: "One month of Netflix Standard plan — stream unlimited movies and series.",
    pointCost: 11000,
    priceMYR: 108,
    vertical: "digital",
    vendor: "Netflix",
    value: "RM 108",
    stock: 80,
  },
  {
    id: "touch-n-go-rm20",
    title: "Touch 'n Go eWallet RM 20",
    description: "RM 20 reload credit to your Touch 'n Go eWallet — use for tolls, shopping & more.",
    pointCost: 1800,
    priceMYR: 20,
    vertical: "digital",
    vendor: "Touch 'n Go",
    value: "RM 20",
    stock: 500,
  },
];
